### ISSUE TITLE
Add a way to track the total number of executed actions

### ISSUE THREAD

**Issue by UnexomWid** [deprimus/Tale#20]
There should be a way to track the exact number of Tale actions that were executed up until a given moment. Here's an idea:

```cs
namespace TaleUtil {
    class Queue {
        public static uint counter = 0;
        ...
        public static TaleUtil.Action Enqueue(TaleUtil.Action act) {
            #if TALE_TRACK_ACTIONS
            ++counter;
            #endif
            
            ...
        }
    }
}
```

This number could then be used, for example, in credits:

```cs
Tale.Exec(() => { totalActions.text = "Total Tale actions: " + (TaleUtil.Queue.counter + N); });

// credits here via Tale.Transform.Move...
// then, go to the main menu
```

This will work because all actions will be placed on the queue (and the counter will be incremented) before that `Exec` action is actually executed. Therefore, the number provided there will be accurate.

**Comment by UnexomWid** [comment]
@AndrewIGD thoughts?

**Comment by AndrewIGD** [comment]
This is a great idea, some are curious to know just how big their game is and a good way to measure that would be through the number of Tale actions. I would also add a method to reset the counter, I personally would also want to count the actions in a scene or in a particular section of a scene, something like `TaleUtil.Queue.ResetCounter()`.

**Comment by UnexomWid** [comment]
So `TaleUtil.Queue.GetCounter()` and `TaleUtil.Queue.ResetCounter()` should work just fine.
